bcgsc/pori_ipr_client

app/views/ReportView/components/GenomicSummary/index.tsx

The label has been changed on the summary page `/report/{ident}/summary`

Change label to 'CD8+ T Cell Score'

---

app/components/DataTable/index.tsx
app/components/DemoDescription/index.scss
app/components/DemoDescription/index.tsx
app/views/ReportView/components/Expression/index.jsx
app/views/ReportView/components/ExpressionCorrelation/index.tsx
app/views/ReportView/components/Immune/index.tsx
app/views/ReportView/components/KbMatches/index.jsx
app/views/ReportView/components/MutationBurden/index.tsx
app/views/ReportView/components/MutationSignatures/index.jsx
app/views/ReportView/components/SmallMutations/index.js
app/views/ReportView/components/SmallMutations/small-mutations.pug
app/views/ReportView/components/TherapeuticTargets/index.tsx
config/webpack/webpack.dev.js

Improvements
- Add demo-only information alerts to some details sections

Add demo mode descriptions to sections

---

app/services/management/auth.js

I ran into this problem earlier today and after some testing this was found to be the solution: https://szoradi-balazs.medium.com/keycloak-login-infinite-loop-9005bcd9a915
Disabling checkLoginIframe solved this

Set checkLoginIframe to false

---

app/views/ReportView/components/Appendices/components/GenomicReportOverview/index.tsx

Based on Erin's updated appendices text document, I have updated the appropriate sections

Update genomic appendix methods text

---

app/views/ReportView/components/MutationBurden/components/TabCards/index.tsx

Remove quality SV count field

---

app/views/ReportView/components/MutationBurden/components/TabCards/index.tsx

This is to fix a tab ordering UI bug when the values aren't uploaded in the correct order. See screenshot:
Fixed version:

Fix ordering of tab labels

---

app/views/ReportView/components/Settings/components/AssociationCard/index.tsx
app/views/ReportView/components/Settings/index.tsx

For use with: https://github.com/bcgsc/pori_ipr_api/pull/55
This PR updates the user association `DELETE` api call to remove a user from a report.

Update delete api call

---

app/views/ReportView/components/CopyNumber/index.tsx
app/views/ReportView/components/Expression/index.jsx
app/views/ReportView/components/ExpressionCorrelation/index.tsx
app/views/ReportView/components/Immune/index.tsx
app/views/ReportView/components/Microbial/index.tsx
app/views/ReportView/components/MutationBurden/index.tsx
app/views/ReportView/components/MutationSignatures/index.tsx
app/views/ReportView/components/PathwayAnalysis/components/Legend/index.tsx
app/views/ReportView/components/PathwayAnalysis/index.tsx
app/views/ReportView/components/StructuralVariants/index.tsx
package-lock.json

For use with: https://github.com/bcgsc/pori_ipr_api/pull/54
This is so images are processed as arrays rather than objects

Handle an array of images from the api

---

app/views/ReportView/components/TherapeuticTargets/components/AutocompleteHandler/index.jsx

Fix for autocomplete loader forever stuck loading. It was hitting a 404 previously

Fix api request to use POST

---

app/components/Image/index.tsx
app/views/GermlineView/components/Report/index.scss
app/views/ReportView/components/CopyNumber/index.tsx
app/views/ReportView/components/ExpressionCorrelation/index.tsx
app/views/ReportView/components/Settings/index.tsx
app/views/ReportView/components/StructuralVariants/index.tsx
app/views/ReportView/index.scss
app/views/ReportsView/index.jsx
config/webpack/webpack.config.js
config/webpack/webpack.prod.js
package-lock.json
package.json

Merge master back to dev

---

app/components/AlertDialog/__tests__/AlertDialog.test.tsx
app/components/AlertDialog/index.tsx

- Added additional handling in AlertDialog component
- Updated type of AlertDialogProps
DEVSU-1694

[DEVSU-1694] bugfix AlertDialog

---

app/views/GermlineView/components/Report/index.tsx

- Add check to filter out empty headernames and action column on exported files
- Updated actions on page to have dropdown menu like other pages
- Updated handleConfirmDelete to handleClose
DEVSU-1650

[DEVSU-1650] Export Germline report

---

app/views/ReportView/components/AnalystComments/components/TextEditor/index.tsx
app/views/ReportView/components/AnalystComments/index.tsx

[DEVSU-1701]
- AnalystComment now checks if is signed first before showing popup
- Fix analystComment editor to not add extra lines on exit

AnalystComment now checks if is signed first before showing popup

---

app/views/ReportView/components/Expression/columnDefs.ts
app/views/ReportView/components/Expression/index.tsx

[DEVSU-1702]
- Add regex to check for new pattern of keys
- Add colId to Actions colDef of Expression so it displays by default
- Update better logic check for hiding columns in Expression
Fixed: Action column enabled by default
Images now are being loaded

update expression with new expDensity img keys

---

app/views/ReportView/components/PharmacoGenomicSummary/index.tsx

- moved probe-test-info into separate API call due to some reports not from GSC not having it and this causes a break in the app
DEVSU-1716

fix: move probe-test-info out from ApiCallSet

---

app/App.tsx
app/appTheme.js
app/services/api/ApiCall.tsx
app/services/api/ApiCallSet.tsx
app/services/api/index.ts

Fix circular dependencies error from eslint

---

app/components/DataTable/components/ImageViewer/index.tsx
app/views/ReportView/components/Expression/index.tsx

Added support for multiple images for expression for a single gene
- Multiple image data support for ImageViewer component
- Expression now checks for ALL images that matches the regex for a gene
- Some eslint fixups
For how this will look for multiple images see [this comment](https://www.bcgsc.ca/jira/browse/DEVSU-1724?focusedCommentId=1551174&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1551174)

[DEVSU-1724] - mult exp density single gene

---

app/views/ReportView/components/CancerPredisposition/index.tsx

- check germline tag, and filter out any variant that is not germline
DEVSU-1746

feat: add filter to kb matches in cancer predisposition

---

config/webpack/webpack.dev.js

Part 1 to just add client Dockerfile to development build
Part 2 will be once we figure out adding the dev image to docker hub
DEVSU-1754

feat: add Dockerfile into dev build variable

---

app/views/ReportView/components/CancerPredisposition/index.tsx
app/views/ReportView/components/Pharmacogenomic/index.tsx

fix: change Germline section table headers

---

app/views/ReportView/components/CancerPredisposition/columnDefs.ts
app/views/ReportView/components/CopyNumber/columnDefs.ts
app/views/ReportView/components/Expression/columnDefs.ts
app/views/ReportView/components/KbMatches/columnDefs.ts
app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts
app/views/ReportView/components/Pharmacogenomic/columnDefs.ts
app/views/ReportView/components/SmallMutations/columnDefs.ts
app/views/ReportView/components/StructuralVariants/columnDefs.ts

just header name changed for now
DEVSU-1125

feat: change cancerRelated headername into inknownledgebasegene

---

app/components/Image/index.tsx
app/views/ReportView/components/CopyNumber/index.tsx
app/views/ReportView/components/StructuralVariants/index.tsx

- Add override to Image component to directly affect props in img tag
DEVSU-1137

feat: SV images now scale to view height

---

app/components/TestInformation/index.tsx
app/components/TestInformation/types.d.ts

The previous work was done to account for pharmacogenomic in TestInfo, the fields just needed an update
DEVSU-1749

feat: add new fields to TestInfo type

---

app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts
package-lock.json
package.json

To keep develop up-to-date, not production critical

Release patch commits to develop

---

app/views/ReportView/components/PharmacoGenomicSummary/index.tsx

[DEVSU-1791] make PCP-TGR summary web and print view similar

---

app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts

[DEVSU-1794] fix: change cancerprdisp evidence into source

---

app/views/ReportView/components/Immune/index.scss

[DEVSU-1678] immune images side by side css fix

---

app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts

- add valueGetter to put reference as evidence if evidence empty and reference is not
DEVSU-1801

[DEVSU-1801] update coldef for pharmacogenomic variant table

---

app/components/Image/index.tsx
app/views/ReportView/components/ExpressionCorrelation/index.tsx

Expression Correlation images having a default of 800px as image width

[DEVSU-1783] exp corr same width

---

app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts
app/views/ReportView/components/ProbeSummary/index.tsx
app/views/ReportView/components/SmallMutations/columnDefs.ts

[DEVSU-1785] add check that *depth fields are not empty when loading reports

---

app/common.d.ts
app/views/AdminView/components/Users/components/AddEditUserDialog/index.tsx
app/views/AdminView/components/Users/index.tsx
package-lock.json
package.json

This took longer than expected, ran into quite a few new issues with using new library and existing issues
Fixes:
- 409 repeat request when user already exists on a project or groups
- ts not recognizing a global variable
New features:
- Added toggle capabilities on project/groups, before it can only add
- Use react-hook-form for form validation

[DEVSU-1728] admin user edit 409

---

app/views/ReportView/components/ExpressionCorrelation/index.tsx

Unsure what the titles for the plots should be, but the images already has the titles
DEVSU-1779

[DEVSU-1779] add BRCA plots to expression correlation

---

app/components/DataTable/components/ColumnPicker/__tests__/ColumnPicker.test.tsx
app/components/DataTable/components/ColumnPicker/index.tsx
app/components/DataTable/index.tsx
app/views/ReportView/components/Expression/index.tsx

Original problem: 
Columns meant to sync across tables did not sync properly, and did not resize properly, see [here](https://www.bcgsc.ca/jira/browse/DEVSU-1825) for problem screenshots
Fixed:

[DEVSU-1825] sync table col toggle

---

app/components/LaunchCell/__tests__/LaunchCell.test.tsx
app/components/LaunchCell/__tests__/__snapshots__/LaunchCell.test.tsx.snap
app/components/LaunchCell/index.tsx

- removed extra action handler onMouseUp
- used Link component for Icon
Screenshots depicting old and new interactions on original ticket

[DEVSU-1693] fix: double window open for Reports link out

---

package-lock.json
package.json

Version bump 

---

app/components/SvgImage/index.tsx

It looks better now that it's autosized 
There is an extra feature where you can display said image in landscape mode as well
Constrained the SvgImg in print mode to adhere to page sizing

[DEVSU-1837] pathwayanalysis svg image fits page

---

app/views/ReportView/components/ProbeSummary/columnDefs.ts
app/views/ReportView/components/ProbeSummary/index.tsx

Removes prefixed gene name for column "Genomic Events" in a probe report

[DEVSU-1802]probing report sv notation

---

app/components/SignatureCard/index.tsx
app/components/SignatureCard/types.d.ts
app/views/ReportView/components/AnalystComments/index.tsx
app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/index.tsx
package-lock.json
package.json

I only see reviewer type for the germline reports, but didn't see anywhere for them to sign, so it's just Genomic/Probe/PCP-TGR for now
Please let me know if I need to add more
Screenshots on ticket in jira

[DEVSU-1847] Add creator signature type to reports

---

app/components/PrintTable/PrintTable.stories.tsx
app/components/PrintTable/index.scss
app/components/PrintTable/index.tsx
app/views/ReportView/components/KbMatches/columnDefs.ts
package-lock.json
package.json

Currently only the print report is edited to allow for stackable rows, AgGrid would need a bit more research
Added storybook stories to illustrate what the table would look like with the different params

[DEVSU-1829] collapsable rows for PrintTable

---

app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/index.tsx

Sorry, it seems like I missed the rendering scheme out for Probe and PCP-TGR from the last PR and just made it for Genomic

[DEVSU-1847] creator sig type -- PCPTGR and Probe to be the same rendering way as Genomic

---

app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/MutationBurden/index.tsx

move tmbur calls out from group call, since it can come back as 404, and makes sure it is silent failure

[DEVSU-1751] tmbur addition #2

---

app/views/ReportView/components/TherapeuticTargets/components/AutocompleteHandler/index.tsx

[this](https://github.com/bcgsc/pori_ipr_client/pull/250/files#diff-caeeb902ebeee40101faa337eccc43a26504bd256d967261d6ae25a22f3030a1R53) line is the line to look for, everything else is just adding typscript

[DEVSU-1859] Unable to add specific variant in IPR therapeutic target table

---

app/common.d.ts
app/views/PrintView/index.tsx
app/views/ReportView/components/AnalystComments/index.tsx
app/views/ReportView/components/RapidSummary/columnDefs.ts
app/views/ReportView/components/RapidSummary/index.tsx
app/views/ReportView/components/Summary/index.tsx

Updates to clinical association table - the drug ordering and rendering
Bugfix to print view not loading properly due to missing attribute for analyst-comment
Screenshots [here](https://www.bcgsc.ca/jira/browse/GERO-304?focusedCommentId=1647068&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1647068)

[DEVSU-1833] rapid template #4

---

app/components/PrintTable/index.scss
app/components/PrintTable/index.tsx
app/views/ReportView/components/GenomicSummary/index.scss
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/PharmacoGenomicSummary/index.scss
app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/index.scss
app/views/ReportView/components/ProbeSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.scss
app/views/ReportView/components/RapidSummary/index.tsx
package-lock.json
package.json

This PR used to be only for Rapid report, but it has expanded into the other report types as well
This is to make sure that the page renders as-is with the correct CSS when the pagedjs library chunks the page for print

[DEVSU-1893] report summary print issue

---

app/views/GermlineView/components/Report/components/Reviews/index.tsx

Perhaps this should be for 1909, but I feel like it's more in-line with 1891 since it's just a field 
The more in-depth changes will be on 1909 PR
DEVSU-1891

[DEVSU-1891] add cgl to review type form submission params

---

app/utils/getImageDataURI.ts
app/views/PrintView/index.tsx
app/views/TemplateView/components/AddEditTemplate/index.tsx

Add helper function and update components for API calls concerning images that have/have not proper headers in return object

[DEVSU-1913] header image upload fix

---

app/views/GermlineView/components/Report/columnDefs.ts
app/views/GermlineView/components/Report/index.tsx

- chore: updated gridApi call accessors instead of direct access
- fix: resizing when "additional info" is shown -- previously table is a jumbled mess, now it properly renders correct boxes
- added feature of setting previously reported by checkbox (disabled for now until API supports it)
Screenshot as is, there is no report with "yes" or "no" so it's all blank for now

[DEVSU-1903] add reported in PCP-TGR field

---

app/context/GermlineReportContext/types.d.ts
app/views/GermlineView/components/Board/columnDefs.ts
app/views/GermlineView/components/Report/columnDefs.ts
app/views/GermlineView/components/Report/components/EditDialog/index.tsx
app/views/GermlineView/components/Report/index.tsx
package-lock.json
package.json

[DEVSU-1909] add extra fields to GSM front page

---

app/common.d.ts
app/views/ReportView/components/RapidSummary/__tests__/RapidSummary.test.ts
app/views/ReportView/components/RapidSummary/__tests__/mockData.js
app/views/ReportView/components/RapidSummary/columnDefs.ts
app/views/ReportView/components/RapidSummary/index.tsx

Changed API calls to `/variant` instead
Did not concatenate rows with same variant but multiple relevance, would mess up rendering in print view
Added some unit tests

[DEVSU-1920] variant unknown sig

---

app/views/ReportView/components/SmallMutations/columnDefs.ts
app/views/ReportView/components/SmallMutations/index.tsx

For screenshots please see [here](https://www.bcgsc.ca/jira/browse/DEVSU-1939?focusedCommentId=1678229&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1678229)

[DEVSU-1939] diseasekiqr insteadof primary

---

app/views/ReportView/components/KbMatches/coalesce.ts
app/views/ReportView/components/KbMatches/columnDefs.ts

[DEVSU-1958] add msi variant type handling for genomic reports

---

app/views/ReportView/components/KbMatches/coalesce.ts
app/views/ReportView/components/KbMatches/index.tsx

- specific error class added
- do not format null/undefined string, just put as empty string instead

[DEVSU-1951]better coalesce entries error handling

---

app/views/ReportView/components/RapidSummary/columnDefs.ts

- also updated VAF% in case one of the number is 0

[DEVSU-1975] use rnaAlt/rnaDepth as backup for alt/total in rapid report

---

app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts

Whoops, forgot to make this PR, so it'll be in the release PR instead and we'll update develop

[DEVSU-1970] better 0 check for PGP-TGR on alt/total

---

app/views/ReportView/components/KbMatches/coalesce.ts
app/views/ReportView/components/KbMatches/columnDefs.ts
app/views/ReportView/components/RapidSummary/columnDefs.ts

Fixes
- tmb variants are now treated the same way where msi variants are on reports
- Undefined/Undefined for alt/total for rapid tables

[DEVSU-1987] kbvariant display

---

app/components/DataTable/components/DetailDialog/index.tsx

- added expandable array of objects as a feature

[DEVSU-1971] detailDialog nested attributes display

---

app/common.d.ts
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/KbMatches/coalesce.ts
app/views/ReportView/components/MutationBurden/index.tsx
app/views/ReportView/components/MutationBurden/types.d.ts
app/views/ReportView/components/RapidSummary/index.tsx

Added relevance and disease as unique key components to kbmatch tables aggregation

[DEVSU-1959] kbmatch aggregation fix

---

app/views/ReportView/components/RapidSummary/columnDefs.ts

Time to divide by 0 and blow up the app

[DEVSU-1962] add RNA stats as backup for cancer Rel alt/total

---

app/components/DataTable/components/ArrayCellRenderer/__tests__/ArrayCellRenderer.test.ts
app/components/DataTable/components/ArrayCellRenderer/index.tsx
app/components/DataTable/components/CivicCellRenderer/index.tsx

Fixes when the first in the list of items in PMIDs is NOT a pmid into rest just text
Further development regarding the whole field would be needed to deal with text and PMID, and which PMID should be the primary entrypoint

[DEVSU-1949] pmid links

---

app/views/ProjectsView/components/AddEditProjectDialog/index.scss
app/views/ProjectsView/components/AddEditProjectDialog/index.tsx

https://www.bcgsc.ca/jira/browse/DEVSU-2005

[DEVSU-2005] Update IPR admin/projects to load project specific data on dialog edit

---

app/utils/getGeneProp.js
app/views/ReportView/components/KbMatches/index.tsx

- Added null/undefined checks
- Added debounce time so the query don't lag the whole page due to multiple row re-renders

[DEVSU-2019] filter bar kb-matches 

---

app/context/ResourceContext/index.tsx
app/context/UserContext/index.tsx
app/hooks/useExternalMode.ts
app/utils/__tests__/checkAccess.test.ts
app/utils/checkAccess.ts

[DEVSU-1967] change prio for checkAccess to prio allowlist

---

app/components/AuthenticatedRoute/index.jsx
app/services/management/auth.js
app/views/AdminView/components/Appendices/index.tsx
app/views/MainView/index.tsx
app/views/ReportView/components/AnalystComments/index.tsx
app/views/ReportView/components/Appendices/components/ReportOverview/index.tsx

Added a modal that starts timer when user logs in
- Modal gives option to ignore or refresh token
Added listener for when user navigates the site to refresh token
Added error handling (notification) when editing Appendices errors out

[DEVSU-2015] kctoken timeout notification

---

app/views/ReportView/components/RapidSummary/columnDefs.ts

~~Drafting this for now, questions to be answered in original ticket~~
Ready for review, confirmed changes needed

[DEVSU-2034] VUS add logic to show gene name + protein change

---

app/components/SvgImage/__tests__/SvgImage.test.tsx
app/components/SvgImage/index.tsx
package-lock.json
package.json

- New Inline-svg library
- Auto portrait/landscape mode for svgs will need more work, turned off for now
Because rolling back to node 12 is waste of effort

[Hotfix][DEVSU-2089] SVG size in print

---

app/components/SvgImage/index.tsx
package-lock.json
package.json

Cleanup of packages and better images centering logic
"Fixed" auto mode of determining if image is supposed to be landscape or portrait (we don't use it atm, but it's a nice to have for a full screen image)

[DEVSU-2089] image size

---

app/views/ReportView/components/RapidSummary/index.tsx

[DEVSU-2076] add sorting alphabetical in VUS render logic

---

app/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
app/components/DataTable/components/ColumnPicker/index.tsx
app/components/DataTable/index.tsx

Fixed some old code typing as well

[DEVSU-2086] DataTable text selectable and copiable

---

.github/workflows/autoprmasterdev.yml
.github/workflows/docker-publish.yml
.github/workflows/npm-test.yml

Doesn't seem to break anything, all good probably
https://github.com/bcgsc/pori_ipr_client/actions/runs/6645232198

[DEVSU-2103] update github action versions

---

app/constants/index.js

bugfix because uh 
I'm bad at coding

[DEVSU-2111] add to suffix constant to satisfy rendering conditions

---

app/components/DataTable/components/ActionCellRenderer/__tests__/ActionCellRenderer.test.tsx
app/components/DataTable/components/ActionCellRenderer/index.tsx

[DEVSU-1188] graphKB linkout now goes to tableview for 1+ kbStatements

---

app/views/ReportView/components/CopyNumber/columnDefs.ts
app/views/ReportView/components/CopyNumber/index.tsx
app/views/ReportView/components/Expression/columnDefs.ts
app/views/ReportView/components/Expression/index.tsx
app/views/ReportView/components/SmallMutations/columnDefs.ts
app/views/ReportView/components/SmallMutations/index.tsx
app/views/ReportView/components/StructuralVariants/columnDefs.ts
app/views/ReportView/components/StructuralVariants/index.tsx

TPM columns now shown by default, any related code to conditionally show it is also removed

[DEVSU-2113] TPM shown by default

---

app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx

- housekeeping of some types
- conditional rendering of TumourSummaryEdit for different report types
- renders form in sections without interdependency

[DEVSU-2078] Tumour summary edit for Rapid report

---

app/components/DataTable/components/GeneViewer/index.tsx
app/components/DataTable/index.tsx

Fixed some imports, and warnings in AgGrid

[DEVSU-2151] allow rows in gene viewer to be selectable

---

app/services/SnackbarUtils.tsx

Most of the changes are just for some more customizability for the snackbar in the future, the most important thing is the close button on line 23-28

[DEVSU-2152] add dismissal button to snackbarutils

---

app/views/TemplateView/components/AddEditTemplate/index.tsx

Logic fault, don't send request with "header" when the image section wasn't messed with

[DEVSU-2166] remove logic check on if no new image uploaded, do not attempt to delete existing header image

---

app/views/ReportView/components/GenomicSummary/index.tsx

change font size of variants in genomicSummary, add padding left instead

[DEVSU-2121] minimize summary part II

---

app/components/ReportAutocomplete/index.tsx
app/components/UserAutocomplete/index.tsx
app/views/ProjectsView/components/AddEditProjectDialog/index.tsx

- The first commit is what matters
- The second commit is QoL upgrade so autocomplete don't spam the API everytime someone types something -- it is debounced now for 500ms before sending request to backend

[DEVSU-2165] new project user undefined

---

app/components/TumourSummaryEdit/index.tsx
app/hooks/useConfirmDialog.tsx
app/views/ReportView/components/GenomicSummary/index.tsx

Not EXACTLY related to DEVSU-2148, but while working on that ticket, the bugs were discovered, this is originally PR #411
Bugs fixed: 
- ApiCallSet settings were incorrect, logic also did not make sense and would cause problems, specifically TumourSummaryEdit/index.tsx line 167-173 
- mutationBurden creation is defaulted to role = primary
- Added default field values to tumourSummaryEdit instead of checking for an object

[DEVSU-2148] tumour summary fixes

---

app/components/SignatureCard/index.scss

- DEVSU-2225
- Adjust signature cards max width to keep all 3 reviewers on the same row

DEVSU-2225 Signature Box Print Format

---

app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx

- Remove editable mutation burden field from tumour summary edit
- Remove Mutation Burden (Mt/Mb) in Genomic and Rapid summary

DEVSU-2239 Remove Editable Mutation Burden Fields

---

app/views/ProjectsView/columnDefs.ts
app/views/ProjectsView/index.tsx

- Fix issue where number of reports was not showing in projects
- Implement admin rights to Number of Reports and Number of User columns
- General linting

DEVSU-2246 Report Counts Missing in Projects

---

app/index.css

- hide headers til 2nd page
- move confidential to footer

[DEVSU-2119] print header updates

---

app/views/MainView/index.tsx

- DEVSU-2277
- Update timeout dialog 'Close' button to 'Logout' button instead
- Update 'Yes' option to 'Stay logged in'

DEVSU-2277 Update Logged In Timeout Dialog

---

app/components/ReportSidebar/index.jsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx
app/views/ReportView/components/Settings/components/AddUserCard/index.tsx
app/views/ReportView/components/Settings/components/Analysis/index.tsx
app/views/ReportView/components/Settings/components/AssociationCard/index.tsx
app/views/ReportView/components/Settings/index.tsx
app/views/ReportView/index.tsx

- DEVSU-2163
- Make completed reports non-editable except for report state
- Allow non-admin and non-manager users to see settings but not able to edit them

DEVSU-2163 Make Completed Reports Selectively Non-Editable

---

app/components/PrintTable/index.scss

[DEVSU-2265](https://www.bcgsc.ca/jira/browse/DEVSU-2265)
* set fixed column width for print table

bugfix/DEVSU-2265 Printed genomic report issues with tables across two tables

---

app/components/NavBar/components/UserSettingsDialog/index.scss
app/components/NavBar/components/UserSettingsDialog/index.tsx
app/components/NavBar/index.tsx

- DEVSU-2308
- Change User Settings to User Profile
- Display table of user information including projects and permission groups
- Remove isSigned check from User Profile since modifying user settings is not dependant on report signature
- Revise api endpoint for user notifications
- Rework overall look and layout of the dialog

DEVSU-2308 User Profile Rework

---

app/components/Sidebar/index.tsx
app/components/UserAutocomplete/index.tsx
app/views/AdminView/components/Users/components/AddEditUserDialog/index.tsx

- Fix button layout for user auto complete textfield
- Enable user to choose whether to copy projects or groups, not both at once
- Code linting

DEVSU-2300 User Add/Edit Dialog UI Improvements

---

app/views/AdminView/components/Groups/index.scss
app/views/AdminView/components/Users/index.scss
app/views/ProjectsView/index.scss

- Adjust height of views with full page data tables and header so the pagination menu does not cutoff at the bottom

bugfix/DEVSU-2299 Pagination Menu Cutoff

---

app/components/DataTable/index.scss
app/components/DataTable/index.tsx
app/components/ReportsTable/index.tsx

- Fix no rows overlay clipping or not displaying for Data Table components (Small Mutations, CNV, Structural Variants, Expression Outliers)
- Code linting

Bugfix/DEVSU-2276 No Rows Overlay Clipped

---

app/common.d.ts
app/components/Image/types.d.ts
app/context/GermlineReportContext/types.d.ts

- Remove redundant data type declarations for Germline report and Image

Feature/DEVSU-2321 Streamline Type Declarations

---

app/components/DataTable/index.scss

remove align-items start in DataTable

bugfix/remove align-items start in DataTable

---

app/views/ReportView/components/TherapeuticTargets/columnDefs.js
app/views/ReportView/components/TherapeuticTargets/index.tsx

- Aggregate gene and variant columns in therapeutic targets print view tables

feat/DEVSU-1028 Aggregate Variants in Therapeutic Targets

---

app/common.d.ts
app/context/GermlineReportContext/types.d.ts
app/views/ReportView/components/Appendices/components/ReportOverview/__tests__/ReportOverview.test.tsx
app/views/ReportView/components/Appendices/components/ReportOverview/index.scss
app/views/ReportView/components/Appendices/components/ReportOverview/index.tsx
app/views/ReportView/components/Appendices/index.tsx

Appendix C tries to load template + project specific text first
If doesn't exist, use default template-specific text 
Remove option to edit template/template + project specific Appendix text in report

[DEVSU-2352] Appendix C text loading

---

app/views/AdminView/components/VariantText/components/AddEditVariantText/index.tsx

Changed Adminview's variant text editor to have cancerType as array of string instead of string
Uses React-hook-form for form validation in the future, right now only needs variant name

[DEVSU-2360] cancer type as list

---

app/components/DataTable/components/HTMLCellRenderer/index.tsx
app/index.scss
app/views/ReportView/components/AnalystComments/index.tsx
app/views/ReportView/components/Appendices/components/ReportOverview/index.tsx

Add spacing for empty paragraphs for spacing

[DEVSU-2375] paragraph spacing

---

app/views/AdminView/components/Groups/columnDefs.ts

[DEVSU-2305] tooltip to group desc

---

app/components/DataTable/components/HTMLCellRenderer/index.tsx
app/components/PrintTable/index.scss
app/components/PrintTable/index.tsx
app/components/SummaryPrintTable/index.tsx
app/index.scss
app/styles/_variables.scss
app/views/AdminView/components/Groups/columnDefs.ts
app/views/AdminView/components/VariantText/components/AddEditVariantText/index.tsx
app/views/ReportView/components/AnalystComments/index.scss
app/views/ReportView/components/AnalystComments/index.tsx
app/views/ReportView/components/Appendices/components/ReportOverview/index.scss
app/views/ReportView/components/Appendices/components/ReportOverview/index.tsx
app/views/ReportView/components/Appendices/index.scss
app/views/ReportView/components/Appendices/index.tsx
app/views/ReportView/components/GenomicSummary/components/KeyAlterations/index.scss
app/views/ReportView/components/PathwayAnalysis/index.scss
app/views/ReportView/components/PathwayAnalysis/index.tsx
app/views/ReportView/components/TherapeuticTargets/index.scss
package-lock.json
package.json

Catch up dev to 6.30 release

---

app/index.scss

- DEVSU-2367
- Revise global scss to enable bullet points in wysiwyg editor again

bugfix/DEVSU-2367 Bullet Points Missing in Analyst Comments

---

app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx

- DEVSU-2369
- Disable "Add to potential therapeutic targets" options for clinical trials in kb matches

bugfix/DEVSU-2369 Disable "Add to Potential Therapeutic Targets" Options for KB Matches Clinical Trials

---

app/views/AdminView/components/VariantText/components/AddEditVariantText/index.tsx

- Small typo fix
- Add edit variant text

bugfix/ Small typo fix for add edit variant text

---

app/views/AdminView/components/Groups/columnDefs.ts

Update list of groups expected in AdminView Groups section.

udpate expected groups

---

app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx

- DEVSU-2392
- Fix null recruitment status error

bugfix/DEVSU-2392 fix null recruitment status error for old reports without kbData property

---

app/views/ProjectsView/components/AddEditProjectDialog/index.tsx
app/views/ProjectsView/index.tsx

See ticket for details on changes 
Add interaction where save button is disabled when something is being created/saved
Add async button for user feedback when something is being loaded

[DEVSU-2393] adminview/project now refreshes whole projects when a project is updated or created

---

app/context/ReportContext/types.d.ts
app/views/ReportView/components/Appendices/columnDefs.js
app/views/ReportView/components/Appendices/index.tsx
app/views/ReportView/components/Appendices/types.d.ts
app/views/ReportView/components/RapidSummary/index.tsx

Use report.sampleInfo for Sample Information instead
Update types related to PR

[DEVSU-2398] rapid patho tc sample info

---

app/views/ReportView/components/PatientInformation/index.tsx
app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/index.tsx

- DEVSU-2399
- Replace reportSampleInfo property with sampleInfo for genomic, pharmacogenomic, and probe summary components

bugfix/DEVSU-2399 fix reportSampleInfo acquisition

---

app/components/ReportsTable/columnDefs.ts
app/utils/reportsColumns.js

Remove column not wanted by CLININFO

remove column not wanted by clininfo

---

app/components/DataTable/index.tsx
app/components/ReportsTable/index.tsx
app/components/ReportsTable/searchColumnDefs.ts
app/components/Sidebar/index.tsx
app/custom.d.ts
app/utils/searchReportsColumns.js
app/views/MainView/index.tsx
app/views/ReportsByVariantView/index.scss
app/views/ReportsByVariantView/index.tsx
app/views/SearchView/index.scss
app/views/SearchView/index.tsx
tsconfig.json

- Add search view to search for reports with specific variant
- Create new reports view for search result
- Validate input variant value
- Add new icon and search menu item to sidebar
- Add support for svg import to typescript config
- Code linting

Feat/DEVSU-2247 Add Search Reports by Variant Feature

---

app/views/AdminView/components/Groups/components/AddEditGroupDialog/index.tsx

Previously supposed to update the list of users whenever the API for edit/add is finished, but since we don't even show the users column anymore, we'll just put callback with null as param -- if we do, however, add that feature back, we can

[DEVSU-2402] update handler on Groups/AddEditUserDialog

---

app/views/MainView/index.tsx
app/views/ReportsByVariantView/index.tsx
app/views/SearchView/index.tsx

[DEVSU-2405] search result pathing fix

---

app/context/ResourceContext/index.tsx
app/views/ReportView/components/Settings/index.tsx
app/views/ReportView/index.tsx

Needs API to not throw 403 when a non-admin/manager edits report status

[DEVSU-2408] add report rule to allow edit on report state

---

app/views/ReportView/components/Settings/components/AddUserCard/index.tsx
app/views/ReportView/components/Settings/components/AssociationCard/index.tsx

Part 2 of ticket, with updated requirements
Also allows assignment of users regardless of report status, if they have permission

[DEVSU-2408] allow report user assignment based on groups instead of report based

---

app/components/SignatureCard/index.tsx
app/services/errors/errorHandler.js
app/services/errors/errors.js
app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx

Add guards to when user's already assigned to report but not signed

[DEVSU-2410] more bugfixes

---

app/context/ResourceContext/index.tsx
app/context/ResourceContext/types.d.ts
app/views/AdminView/components/Users/components/AddEditUserDialog/index.tsx
app/views/AdminView/components/Users/index.scss

Add allProjectsAccess and make default value for project/groups to be null instead so the form sees empty array as "dirty"

[DEVSU-2427] bugfix: add user dialog

---

app/views/AdminView/components/Users/components/AddEditUserDialog/index.scss
app/views/AdminView/components/Users/components/AddEditUserDialog/index.tsx

- Realign checkbox to add user to graphkb in add edit user dialog

Chore: DEVSU-2433 Realign checkbox to add user to graphkb in add edit user dialog

---

app/views/AdminView/components/Users/components/AddEditUserDialog/index.scss
app/views/AdminView/components/Users/components/AddEditUserDialog/index.tsx

- DEVSU-2479
- Add keycloak notice message to add edit user dialog

feat/DEVSU-2479 Add keycloak notice message to add edit user dialog

---

app/views/ReportView/components/AnalystComments/index.tsx

[DEVSU-2438] bugfix: add null check to updated comment instead of checking loose true/false

---

app/views/ReportView/components/KbMatches/coalesce.ts

- DEVSU-2516
- Fix coalesce logic for statements with multiple kbMatches

bugfix/DEVSU-2516 Rows with different contexts being merged in kbmatches tables

---

app/views/ReportView/components/TherapeuticTargets/components/EditDialog/index.tsx

- DEVSU-2486
- Fix bug where empty variant field leads to error even when signature is selected instead of gene

bugfix/DEVSU-2486 Cannot add new signature type variant to therapeutic targets table

---

app/components/Sidebar/index.tsx

[DEVSU-2546](https://www.bcgsc.ca/jira/browse/DEVSU-2546): 
- update search by kbmatches sidebar highlight conditions to avoid it highlighted when knowledge base search

DEVSU-2546-KB-Matches-active-link-set-incorrectly 

---

app/views/ReportView/components/KbMatches/coalesce.ts
app/views/ReportView/components/KbMatches/index.tsx

- Update coalesceEntries logic for kbMatches
- Code lint

DEVSU-2557 supplemental code change

---

app/views/AdminView/components/VariantText/index.tsx

[DEVSU-2549](https://www.bcgsc.ca/jira/browse/DEVSU-2549)
- fix bad request error when trying to edit variantText comment

bugfix/DEVSU-2549 cancerType not a valid property for variant texts

---

app/views/ReportView/components/KbMatches/index.tsx

- Supplement to DEVSU-2557 main PR
- Implement check if a row is coalesced and move all individual statements in the row to another table
- Implement moving rows to high evidence table (top table)

DEVSU 2557 kbMatch table reassign coalesced rows fix

---

app/views/ReportView/components/SmallMutations/columnDefs.ts

- DEVSU-2563
- Fix bug where unhidden columns are not displayed in small mutations
- Add VAF% column and calculations to small mutations

bugfix/DEVSU-2563 Small mutation default columns

---

app/components/IPRWYSIWYGEditor/index.tsx
app/views/ReportView/components/AnalystComments/index.tsx

Add better null/undefined checks to the `IPRWYSIWYGEditor`
Some styling autoformats

[DEVSU-2589] Analyst comment disappearing onClose

---

app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx

- [DEVSU-2597](https://www.bcgsc.ca/jira/browse/DEVSU-2597)
- Fix bug where kbmatchtag could be undefined in kbData in kbMatchesActionCellRenderer dependency array

DEVSU-2597 Fix undefined 'kbmatchTag' error in kb matches view

---

app/App.tsx
app/views/TemplateView/index.tsx
package-lock.json
package.json

DEVSU-2581 Update TemplateView to use react-query
- import and add QueryClientProvider to App.tsx
- include 'react-query' in package.json and package-lock.json
- change data fetching in TemplateView to use react query

DEVSU-2581 Update TemplateView to use react-query

---

app/utils/getGeneProp.js
app/views/ReportView/components/CancerPredisposition/columnDefs.ts
app/views/ReportView/components/KbMatches/columnDefs.ts
app/views/ReportView/components/Pharmacogenomic/columnDefs.ts

- [DEVSU-2591](https://www.bcgsc.ca/jira/browse/DEVSU-2591)
- Fix issue where undefined properties in variant would crash filter table text search bar in kbmatches view

DEVSU-2591 Using searchbar on IPR genomic report KB match page makes page go blank

---

app/components/IPRWYSIWYGEditor/index.tsx

bugfix: reset editor state onClose for IPRWYSIWYGEditor

---

app/views/ReportView/components/TherapeuticTargets/components/TherapeuticTargetPrintTable/index.tsx

add support for valueGetter in the colDefs in `TOPrintTable`

[DEVSU-2500 part II] add valueGetter check to TOPrintTable component

---

app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/defaultStates.ts
app/views/ReportView/components/GenomicSummary/index.tsx

Same as #642 , this is for testing on develop

[DEVSU-2590 part II] genometmb remove old attr (develop)

---

app/views/AdminView/components/Users/components/AddEditUserDialog/index.tsx

Admin/User add dialog didn't have logic when user is being edited
- styling ts fixups

[DEVSU-2633] add logic for snackbar when user exists on creation

---

app/views/PrintView/index.tsx

[DEVSU-2658] rapid print report name change v2

---

app/components/DataTable/components/CustomSetFilter/index.tsx
app/components/ReportsTable/searchColumnDefs.ts
app/utils/searchReportsColumns.js

- DEVSU-2679
- Fix bug where custom set filter incorrectly splits variant names due to inclusion of delimiter

DEVSU-2679 IPR search some SV strings w spaces parsed incorrectly in filter

---

app/views/ReportsSearchView/index.tsx
app/views/SearchView/index.tsx

- DEVSU-2682
- Encode search url

DEVSU-2682 Encode Search URL

---

app/views/ReportView/components/AnalystComments/index.tsx

- DEVSU-2697
- Make edit button in analyst comment float and stay in fixed position even when view is scrolling

DEVSU-2697 Analyst Comments Edit Button Fixed Position

---

app/components/ReportsTable/searchColumnDefs.ts

- DEVSU-2715
- Remove redundant arraycellrenderer in searchColumnDefs since the joins are used in util function

DEVSU-2715 Whitescreen on search result
