bcgsc/pori_ipr_client

app/views/ReportView/components/GenomicSummary/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx

Added 2 percent signs in the summary page to make the field a bit clearer

Add percent sign to tumour content fields

---

app/views/ReportView/components/ProbeSummary/columnDefs.ts

The upload script has been updated to use the RNA/DNA data for the sample field instead of the library name. This is to show this field in the genomic events table for probe reports.

Display sample field in genomic events table

---

app/views/ReportView/components/GenomicSummary/components/PatientEdit/index.jsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/index.tsx

> we recently looked into it, and Jess confirmed that the field we call 'sex' should actually be called 'gender', as this comes from CAIS and is self-reported patient gender. Could this field name be changed on the summary page?
- Changed sex to gender

Change sex label to gender

---

app/views/ReportView/components/MutationBurden/index.tsx

This will allow the msi scatter plot to show up on the mutation burden page as the return object is `{msi.scatter: {image}}`

Fix accessor for scatter plot

---

app/services/management/auth.js
app/views/LoginView/index.jsx

Previously the `.success` method would always be called even if there was an error it seems. If an error was thrown then it wouldn't be handled properly in `.success` which resulted in a blank page.
This has always been an issue, but the `checkIframe` option which we recently had to disable was hiding this behaviour. The iframe would perform the token check after the error and redirect to the login page

Fix keycloak login throwing error in success method

---

app/components/Sidebar/index.js
app/components/Sidebar/sidebar.pug

The react `window` object has the `window._env_.CONFIG` attached to it while the angular one doesn't. This fixes the link not being defined

Access react window instead of angular window

---

app/views/ReportView/components/CopyNumber/index.tsx

Fix index from 1 - 5 instead of 0 - 4 so all copy plots are displayed

Fix copy plot image cut off

---

app/views/GermlineView/components/Report/columnDefs.ts
app/views/GermlineView/components/Report/index.tsx

[DEVSU-1714]
- update colDefs for GermlineView's dbSNP column to take into new format provided by the API
- make columns in GermlineView's Variant section resizable
looks like this now

feat: update germlineView coldefs

---

app/views/ReportView/components/PharmacoGenomicSummary/index.tsx

[DEVSU-1716]
Use new API of `kb-matches` for Cancer Predisposition Variant instead of `small-mutations`
used IPRStaging for grabbing newer data for type pharmacogenomic report in testing, here are the result

fix: update API call for cancerPredisposition variant section of summary

---

config/webpack/webpack.dev.js

Removed packing the dockerfile into the /dist directory, since we'll be moving the file via bamboo build anyway, and it seems like a bad idea to have the dockerfile showing publically

chore: return API call onto dev

---

app/components/PrintTable/index.scss

[DEVSU-1795] - add css rule where table row does not break over new page

---

app/components/DataTable/index.tsx

Looks like the cut off text just by a little by agGrid was due to not enough inherent padding ... the default value for `autoSizePadding` is actually 4, but 1 looks to be enough
DEVSU-1793

[DEVSU-1793] better column sizing on tables

---

app/components/DataTable/index.scss
app/index.scss

This rule applies to all tables on this application instead of JUST PCP-TGR
For the `.ag-center-cols-clipper` rule it's to prevent the extra pixels on the table 
**Old:**
**New:**

[DEVSU-1820] remove double line from last row

---

app/views/ReportView/components/PharmacoGenomicSummary/index.tsx

[DEVSU-1814]add filtering on PCPTGR summary page for germline variants

---

app/views/ReportView/components/Expression/columnDefs.ts

`report/b35ba4cd-a826-47cb-a5b6-b12f8d960ad6/expression`
now correctly shows the internal pancancer params

[DEVSU-1848] Internal Pancancer colDef updates to correct ones

---

.github/workflows/autoprmasterdev.yml

Been messing with github actions a little bit, this makes an auto-pr from master into develop to update 
Looks to work here, once the master branch is update the github-action would make the PR and wait for whomever to approve
https://github.com/kttkjl/workflow_test/pulls?q=is%3Apr+is%3Aclosed

[no-ticket] add github action to make PR to develop once master has a release merged in

---

app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/MutationBurden/index.tsx

Addressed user feedback
- **CDS Indel TMB (mut/mb)** instead of **CDS Indel TMBs (mut/mb)**
- 2 decimal places for **Genome TMB** field
Some API call code reduction in tmbur

[DEVSU-1751] tmbur to genomic #2

---

app/common.d.ts
app/views/ReportView/components/RapidSummary/columnDefs.ts
app/views/ReportView/components/RapidSummary/index.tsx

Tables are now correctly shown, and data connected for 
```
"Genomic Events with Therapeutic Association"
"Genomic Events with Cancer Relevance"
```
results for these two tables are filtered by unique based on the shown columns
Screenshots regarding the two tables [here](https://www.bcgsc.ca/jira/browse/DEVSU-1833?focusedCommentId=1639871&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1639871)

[DEVSU-1833] rapid template update #3

---

app/views/ReportView/components/RapidSummary/columnDefs.ts
app/views/ReportView/components/RapidSummary/index.tsx

Changes by the suggestions
- Could we make the Mutation burden field name to be consistent with the genomic report. Preferred method is to use Genome TMB (mut/mb): 2.00 for example.
- Could we rename the tumour content field to Pathology Tumour Content rather than Initial Tumour Content, use Patho TC as this new attrbute
- Could we add a VAF column? (Rapid report only, not for the genomic or TGR) This could be longer term update, but it will greatly increase the usefulness of this data to the clinicians I think. The formula is VAF = Alt read counts/Total read counts.

[DEVSU-1894] rapid report tumor summary changes

---

app/services/api/ApiCallSet.tsx
app/views/ReportView/components/RapidSummary/index.tsx
tsconfig.json

app breaks whenever rapid calls aren't all found, this separates concerns and give error messages whenever and still loads the page with whatever data it can grab

[DEVSU-1912] separate rapid api calls

---

app/components/PatientEdit/index.tsx
app/context/ReportContext/types.d.ts
app/views/ReportView/components/RapidSummary/index.tsx

Made the `PatientEditDialog` component a bit more robust, now offers the feature to have different fields for the edit on different types of reports, should we get there -- this change was made because `oncotreeTumourType` was limited to just rapid, but the `PatientEdit` component was shared between multiple report types (all of them actually)

[DEVSU-1932] tumourtype to rapid

---

app/components/ReportSidebar/index.jsx

Been bothering me too long, the right side bar didn't have the option to open new tabs, as the link it is referencing to is missing the report id

[no-ticket] allow ReportSidebar to open new tab when middle-mouse button clicked

---

app/views/PrintView/index.tsx

Add logic when diagnosis is "undertermined", do not render the value
Cleaned up text rendering logic for Biopsy so it's cleaner
[Fixed screenshot here](https://www.bcgsc.ca/jira/browse/DEVSU-2024?focusedId=1773636&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1773636)

[DEVSU-2024] undetermined diagnosis field

---

app/views/ReportView/components/RapidSummary/index.tsx

stopgap measure to prevent front-end from breaking due to wrong data
More comprehensive fix exists in PR for DEVSU-2009

[no-ticket] more robust rendering for util functions for table 1 rapid

---

app/common.d.ts
app/components/DataTable/index.tsx
app/views/ReportView/components/KbMatches/index.tsx
app/views/ReportView/components/RapidSummary/components/VariantEditDialog/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx

Commit [35e3d8d](https://github.com/bcgsc/pori_ipr_client/pull/404/commits/35e3d8d6685fbf615cad692644f585fed6d96197)
- Fixes a bad param pass that was missed into DataTable component into KbMatchesActionCellRenderer
- Fixes code missed in DEVSU-1966 (this/otherCancer -> highEvidence)

[DEVSU-2175] add del calls to kbmatches on rapid report table 1

---

app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/SmallMutations/columnDefs.ts
app/views/ReportView/components/StructuralVariants/columnDefs.ts

PR to develop for dev first, then back to release branch
**hotfix: release 6.25.0 fixes**
- DEVSU-2133: Z score column not capitalized correctly
- DEVSU-2148: tmburMutBur was not added to the tumour edit form

[hotfix] release 6.25.0 fixes

---

app/components/TumourSummaryEdit/index.tsx

The correct way was to remove the nested attribute, instead of adding `?` for `mutationBurden?.totalMutationsPerMb` in dependency array

6.25.1 fixes

---

app/components/DataTable/index.tsx
app/views/ReportView/components/TherapeuticTargets/index.tsx

Sometimes the tables for rankings are 0 based, and sometimes 1 based, leading to ordering madness when table row is moved around
- sorts based on rank from backend, then forces to indexed 0 ranks, increments of 1
- typescript type fixings

[DEVSU-2177] bugfix: add front-end datafix to TO table rankings

---

app/common.d.ts
app/components/TumourSummaryEdit/index.scss
app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/MutationBurden/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx

- DEVSU-2231
- Display adjusted TMB and adjusted TMB comment on both report summary section and Mutation Burden table
- Add front end enforcement when adjusted TMB score is edited without accompany explanation comment
- Add check box to toggle visibility of TMB fields on both report summary and Mutation Burden table

Feat/DEVSU-2231 Display Adjusted TMB Fields

---

app/common.d.ts
app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/Immune/columnDefs.ts
app/views/ReportView/components/RapidSummary/index.tsx

- DEVSU-2240
- Add editable Pediatric score, percentile, and comment fields for T Cell CD8 in tumour summary
- Add dynamic labeling for CD8+ score in genomic and rapid summary
- Add pediatric score, percentile, and comment columns to immune section
- Enforce edit ability to only Pediatric case types from front end

Feat/DEVSU 2240 Editable Pediatric CD8+ T Cell Score and Percentile Fields

---

app/components/PrintTable/index.scss
app/components/SummaryPrintTable/index.tsx
app/index.css
app/views/PrintView/components/RunningCenter/index.tsx
app/views/PrintView/components/RunningRight/index.tsx
app/views/PrintView/index.tsx
app/views/ReportView/components/GenomicSummary/components/KeyAlterations/index.scss
app/views/ReportView/components/GenomicSummary/components/KeyAlterations/index.tsx
app/views/ReportView/components/GenomicSummary/index.scss
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx
app/views/ReportView/components/Summary/index.tsx
app/views/ReportView/components/TherapeuticTargets/index.scss
app/views/ReportView/components/TherapeuticTargets/index.tsx

- DEVSU-2117
- Split genomic summary component to patient info + tumour summary and key alterations
- Rearrange therapeutic targets and chemoresistance tables in between tumour summary and key alterations
- Reduce white space and padding for therapeutic targets and chemoresistance table rows
- Make therapeutic targets and chemoresistance tables full width in print mode, even when empty
- Lighten and thin out bottom border for therapeutic targets and chemoresistance table rows

DEVSU-2117 Reorganize Genomic Report Print

---

app/common.d.ts
app/components/TumourSummaryEdit/index.scss
app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx

- DEVSU-2244
- Add percentileHidden to ImmuneType
- Add visibility toggle for CD8+ percentile in tumour summary edit
- Enforce visibility rule for CD8+ percentile on genomic and rapid summaries
- Adjust size and margin of visibility toggles for both CD8+ percentile and TMB information

DEVSU-2244 CD8+ T Cell Percentile Visibility Toggle

---

app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx

- Add mutation burden back to genomic summary and rapid summary so old reports still display existing values
- Remove redundant state property of totalMutationPerMb in tumour summary edit now that Mutation Burden is not editable anymore
- DEVSU-2239

DEVSU-2239 Add Mutation Burden back to Genomic Summary and Rapid Summary

---

app/views/ReportView/components/TherapeuticTargets/components/AutocompleteHandler/index.tsx

Changes min chars for autocomplete Gene search to 1. This is because gene symbols can be shorter than 3 characters, and with the current setup it's not possible to add a new row in the Potential Therapeutic Options table (for instance) for the variant 'FH frameshift mutation'.

reduce min chars for autocomplete to 1

---

app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx
app/views/ReportView/components/TherapeuticTargets/components/EditDialog/index.tsx
app/views/ReportView/components/TherapeuticTargets/index.tsx

- Re-enable options to add kb statements to potential therapeutic options
- Add enforcement to check if potential therapeutic option already exists and display appropriate snackbar notification
- Update therapeutic options view to reflect change immediately after an entry is deleted and display snackbar notification
- Code linting

Feat/DEVSU-2290 Rework Options to Add KB Matches Statements to Therapeutic Options

---

app/commonComponents.d.ts
app/components/ReportSidebar/index.jsx
app/views/MainView/index.tsx
app/views/PrintView/index.scss
app/views/PrintView/index.tsx
app/views/ReportView/components/GenomicSummary/components/KeyAlterations/index.scss
app/views/ReportView/components/GenomicSummary/components/KeyAlterations/index.tsx
app/views/ReportView/components/GenomicSummary/index.tsx
app/views/ReportView/components/TherapeuticTargets/index.tsx

- Rename 'stable' and 'beta' prints to ' Standard Layout' and 'Condensed Layout'
- Change naming conventions in code base to be consistent with new names
- Remove Condensed Layout print option for non-genomic reports
- Remove useless escapes in regex paths for report side bar component

DEVSU-2267 - Rework 'Beta' Print View

---

app/components/UserAutocomplete/index.tsx
app/views/AdminView/components/Groups/components/AddEditGroupDialog/index.tsx
app/views/AdminView/components/Users/components/AddEditUserDialog/index.tsx

- Add user auto complete to add edit user dialog to allow for copying of an existing user's projects and permissions
- Set rules enforcing that admin users can add new user to all projects and groups, but managers can only add new user to non admin groups and the same projects they have
- Change add button for user auto complete to arrow icon for more flexibility in purposes
- Revamp add edit user dialog look and layout
- Code linting

DEVSU-2300 User Projects and Permissions Copy

---

app/components/DataTable/components/HyperlinkCellRenderer/index.tsx
app/components/DataTable/components/PogHyperlinkCellRenderer/index.tsx
app/components/DataTable/index.tsx
app/utils/reportsColumns.js
app/views/MyReportsView/index.tsx
app/views/PatientsView/index.tsx
app/views/ReportView/components/ExpressionCorrelation/components/CorrelationPlot/columnDefs.js
app/views/ReportsView/index.tsx

- Add cell renderer for data table so that pairwise expression correlation pog IDs can be used as hyperlinks to display specific Patients Views
- Fix report type in Patients View to be in line with other reports view

feat/DEVSU-2138 POG Hyperlinks in Pairwise Expression Correlation Table

---

app/components/TumourSummaryEdit/index.tsx
app/views/ReportView/components/TumourSummary/index.tsx

- activate captiv-8 on genomic
- move tumourSummary/microbial default props to further down component tree

[DEVSU-2351] Activate captiv-8 field to be editable on genomic report

---

app/components/DataTable/components/HTMLCellRenderer/index.scss
app/components/DataTable/components/HTMLCellRenderer/index.tsx
app/components/DataTable/components/ToolTip/index.scss
app/components/DataTable/components/ToolTip/index.tsx
app/components/DataTable/index.tsx
app/components/ReportsTable/columnDefs.ts
app/components/ReportsTable/index.tsx
app/index.scss
app/styles/reset.css
app/views/AdminView/components/Appendices/columnDefs.ts
app/views/AdminView/components/Groups/columnDefs.ts
app/views/AdminView/components/Groups/index.tsx
app/views/TemplateView/columnDefs.ts
package-lock.json
package.json

AdminViews for multi-line cells fix -- looks a bit better
- Added HTMLCellRenderer to render cells with HTML as content to automatically fit height on load
- Admin Groups + Templates auto height (kinda works)
Added pilot tooltip component on ReportsTable for some columns that are known to be long

[DEVSU-2319] tooltips long string data

---

app/context/ReportContext/types.d.ts
app/views/ReportView/common.ts
app/views/ReportView/components/PharmacoGenomicSummary/columnDefs.ts
app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/ProbeSummary/columnDefs.ts
app/views/ReportView/components/ProbeSummary/index.tsx
app/views/ReportView/components/ProbeSummary/types.d.ts
app/views/ReportView/components/RapidSummary/columnDefs.ts
app/views/ReportView/components/RapidSummary/index.tsx

- Update `sampleInfo` to `reportSampleInfo`  for report-specific sample information data access on Rapid, Probe, and Pharmacogenomic reports
- Some ts type fixes as files updated

[DEVSU-2337] use reportSampleInfo instead of sampleInfo

---

app/components/PrintTable/index.scss
app/components/PrintTable/index.tsx
app/components/SummaryPrintTable/index.tsx
app/styles/_variables.scss
app/views/ReportView/components/AnalystComments/index.scss
app/views/ReportView/components/Appendices/components/ReportOverview/index.scss
app/views/ReportView/components/Appendices/components/ReportOverview/index.tsx
app/views/ReportView/components/Appendices/index.scss
app/views/ReportView/components/Appendices/index.tsx
app/views/ReportView/components/GenomicSummary/components/KeyAlterations/index.scss
app/views/ReportView/components/PathwayAnalysis/index.scss
app/views/ReportView/components/PathwayAnalysis/index.tsx
app/views/ReportView/components/TherapeuticTargets/index.scss
package-lock.json
package.json

PrintTables now take first row of rendered table to determine widths for all tds 
Last row of cut-off table doesn't get thrown out
Fixed some styling here and there
There is a known bug where sometimes a auto-row-spanned row is split into two 
Reports to test on:
Genomic: 1461, 1797

[DEVSU-2265] dynamic split table

---

app/views/AdminView/components/Groups/index.tsx

Adds display of missing groups - create report access, variant-text edit access, and report assignment access

add three remaining groups to displayed groups

---

app/views/ReportView/components/Settings/index.tsx

Allow adding assigning users to probe-type reports. This enables users to sign them which is currently not possible without manager or admin status.

allow setting users for tgr type report

---

app/components/SignatureCard/index.tsx

Fixes bug preventing signatures from being signed when there are is no preexisting signatures record for the report.
Ensures that the reportUser role sent to the api when a signature is attached by a user who does not already have a reportUser role, is one of the expected reportUser role values.

DEVSU-2431-fix unexpected json error when signing

---

app/components/SignatureCard/index.tsx

In PrintView, does not display signatures that have not been signed.

do not render missing sigs in print

---

app/views/ReportView/components/PharmacoGenomicSummary/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx
app/views/ReportView/components/TherapeuticTargets/index.tsx

Disabling the coalesce disables IPR level sorting as well, since this is temporary, probably not worth to explore it and look for a new library on displaying instead

[DEVSU-2540] temporarily disable coalesce on all print tables

---

app/common.d.ts
app/components/TumourSummaryEdit/index.tsx
app/utils/getMicbSiteIntegrationStatusLabel.ts

- DEVSU-2552
- Requires DEVSU-2552 API change PR [https://github.com/bcgsc/pori_ipr_api/pull/416]
- Add microbialHidden flag to microbial type for toggling visibility of microbial entries in genomic summary
- Add visibility toggle to microbial chips in tumour summary edit
- Update microbial display util function to filter out hidden entries

feat/DEVSU-2552 Add visibility toggle to microbial chips in tumour summary edit

---

app/components/DataTable/components/KbMatchesActionCellRenderer/index.tsx
app/components/DataTable/index.tsx
app/components/ReportSidebar/index.tsx
app/context/KbMatchesMoveDialogContext/KbmatchesMoveDialogContext.tsx
app/views/ReportView/components/KbMatches/coalesce.ts
app/views/ReportView/components/KbMatches/columnDefs.ts
app/views/ReportView/components/KbMatches/index.tsx

Multi-row select for tables of KbMatches view for Genomic 
Ctrl-click multi selection, or shift (but that does text selecting too)
- Right click will bring out context menu for moving KbStatementIds to target table, if selected, prompts dialog
- Menu beside table name will have extra option of toggling the dialog as well
Single selection:
- Right clicking a single row will bring out context menu to toggle dialog
- Selecting a row-specific action menu will also do the same
Known behaviors:
- After moving statements, if there are any lingering entries (if you planned to move all of them), then it is IPR-API's duplicate entries with different idents, there is no way of selecting for priority either because the creation time is the same

[DEVSU-2557] kbmatch table re-assignment

---

app/utils/kbMatchStatementsGeneValueGetter.ts
app/utils/kbMatchStatementsKnownVarValueGetter.ts
app/utils/kbMatchStatementsObsVarValueGetter.ts
app/views/ReportView/components/KbMatches/coalesce.ts

- DEVSU-2603
- Fix coalesce issue where kbMatches arrays get nested in each other unintentionally when statements are coalesced. Now kbMatches records are concatenated in the same array, and only when they have different kbVariantId
- De-duplicate gene names, known variants, and observed variants in cases where there are multiple coalesced kbMatches
- Remove redundant bucket key creation logic

DEVSU-2603 Fix kbMatchedStatements coalesce logic

---

app/views/ReportView/components/TherapeuticTargets/columnDefs.js
app/views/SearchView/index.tsx

- DEVSU-2638
- Rearrange search categories to put key variant as default category per clininfo request
- Remove 'default' in therapeutic targets column defs export to prevent warnings

DEVSU-2638 Set key variant as default search category

---

app/views/ReportView/components/TherapeuticTargets/columnDefs.js
app/views/SearchView/index.tsx

- DEVSU-2638
- Rearrange search categories to put key variant as default category per clininfo request
- Remove 'default' in therapeutic targets column defs export to prevent warnings

DEVSU-2638 Key Variant as Default Search Category

---

app/components/VariantEditDialog/index.tsx
app/views/ReportView/components/RapidSummary/components/RapidVariantEditDialog/index.tsx
app/views/ReportView/components/RapidSummary/index.tsx

Logic for checking if `kbMatchedStatements` on a drug deletion were incorrect, logic loop kept looping itself causing all the ids to be up for deletion
- fixed ids to delete logic on drug updates for RapidVariantEditDialog
- rename Rapid/VariantEditDialog to RapidVariantEditDialog to avoid ambiguity with common component 
- fixed some tabbing problems in code

[DEVSU-2635] Rapid/VariantEditDialog logic fix

---

app/components/TumourSummaryEdit/index.tsx
app/utils/getMostCurrentObj.js
app/views/ReportView/components/RapidSummary/index.tsx
app/views/ReportView/components/TumourSummary/index.tsx

- [DEVSU-2649](https://www.bcgsc.ca/jira/browse/DEVSU-2649)
- Display msi score and msi status for rapid report, including FFPE samples
- Enable msi score to be editable in tumour summary edit

DEVSU-2649 Display MSI Status FFPE Rapid Reports

---

app/constants/index.js
app/views/SearchView/index.tsx

- DEVSU-2677
- Fix bug where numpad enter key would delete search keyword instead of adding search chip

DEVSU-2677 IPR search - num pad "enter" and main keyboard "enter" function differently

---

app/views/ReportView/components/TherapeuticTargets/index.tsx

- DEVSU-2707
- Enable row reordering for chemoresistance table

DEVSU-2707 Can't reorder rows in chemoresistance table
